apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    application: app-de-ejemplo
    template: eap72-basic-s2i
    template.openshift.io/template-instance-owner: eb837fe9-661b-4c19-befc-78ba50428e93
    xpaas: 1.1.0
  name: app-de-ejemplo
  selfLink: /apis/build.openshift.io/v1/namespaces/dev/buildconfigs/app-de-ejemplo
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: app-de-ejemplo:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/GeraldSP/holamundo.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: MAVEN_MIRROR_URL
      - name: MAVEN_ARGS_APPEND
        value: -Dcom.redhat.xpaas.repo.jbossorg
      - name: ARTIFACT_DIR
      forcePull: true
      from:
        kind: ImageStreamTag
        name: jboss-eap72-openshift:1.1
        namespace: openshift
      incremental: true
    type: Source
  successfulBuildsHistoryLimit: 5
