apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    application: app-de-ejemplo
    template: eap72-basic-s2i
    template.openshift.io/template-instance-owner: eb837fe9-661b-4c19-befc-78ba50428e93
    xpaas: 1.1.0
  name: app-de-ejemplo
  selfLink: /apis/image.openshift.io/v1/namespaces/dev/imagestreams/app-de-ejemplo
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/app-de-ejemplo
