apiVersion: v1
data:
  APPLICATION_NAME: YXBwLWRlLWVqZW1wbG8=
  AUTO_DEPLOY_EXPLODED: ZmFsc2U=
  CONTEXT_DIR: ""
  IMAGE_STREAM_NAMESPACE: b3BlbnNoaWZ0
  MAVEN_ARGS_APPEND: LURjb20ucmVkaGF0LnhwYWFzLnJlcG8uamJvc3Nvcmc=
  MEMORY_LIMIT: M0dp
  SOURCE_REPOSITORY_REF: ""
  SOURCE_REPOSITORY_URL: aHR0cHM6Ly9naXRodWIuY29tL0dlcmFsZFNQL2hvbGFtdW5kby5naXQ=
kind: Secret
metadata:
  creationTimestamp: null
  generateName: eap72-basic-s2i-parameters-
  selfLink: /api/v1/namespaces/dev/secrets/eap72-basic-s2i-parameters-g6jhw
type: Opaque
